absolute_urls: false
timezone: 'Europe/Berlin'

home:
  alias: '/about'

pages:
  theme: antimatter
  markdown:
    extra: false
  process:
    markdown: true
    twig: false

cache:
  enabled: false
  check:
    method: file
  driver: auto
  prefix: 'g'

twig:
  cache: true
  debug: true
  auto_reload: true
  autoescape: false

assets:
  css_pipeline: false
  css_minify: true
  css_rewrite: true
  js_pipeline: false
  js_minify: true

errors:
  display: false
  log: true

debugger:
  enabled: false
  twig: true
  shutdown:
    close_connection: true
gpm:
  releases: stable
  verify_peer: true

languages:
  translations: true
  supported:
    - de
    - en
