baseURL = "http://kanthaus.gitlab.io/"
languageCode = "en-us"
DefaultContentLanguage = "de"
title = "Kanthaus"
theme = "minimal"

[params]
    author = "kanthaus"
    accent = "purple"
    showBorder = false
    backgroundColor = "white"
    font = "Raleway" # should match the name on Google Fonts!
    highlight = true
    highlightStyle = "solarized-dark"
    highlightLanguages = ["go", "haskell", "kotlin", "scala", "swift"]

[[menu.main]]
    url = "/"
    name = "Home"
    weight = 1

[[menu.main]]
    url = "/docs"
    name = "Documents"
    weight = 2

[[menu.main]]
    url = "/meetings"
    name = "Meetings"
    weight = 3

[[menu.main]]
    url = "/contact/"
    name = "Contact"
    weight = 4


[Languages]
[Languages.en]
    copyright  = "<a href='https://creativecommons.org/publicdomain/zero/1.0/' style='text-decoration: none; color: #777777'> CC0; no rights reserved </a>"
   description = "sharing instead of exchanging"


[Languages.de]
    copyright  = "<a href='https://creativecommons.org/publicdomain/zero/1.0/' style='text-decoration: none; color: #777777'> CC0; keine Rechte vorbehalten </a>"
   description = "Teilen statt Tauschen"
# Social icons to be shown on the right-hand side of the navigation bar
# The "name" field should match the name of the icon to be used
# The list of available icons can be found at http://fontawesome.io/icons/

[[menu.icon]]
    url = "dmwebb@gmail.com"
    name = "envelope-o"
    weight = 1

[[menu.icon]]
    url = "https://gitlab.com/kanthaus/"
    name = "gitlab"
    weight = 2

[[menu.icon]]
    url = "/index.xml"
    name = "rss"
    weight = 3
