baseURL = "https://kanthaus.online/"
DefaultContentLanguage = "de"
title = "Kanthaus"
theme = "minimal"

[params]
    author = "kanthaus"
    accent = "purple"
    showBorder = false
    backgroundColor = "white"
    font = "Raleway" # should match the name on Google Fonts!
    highlight = true
    highlightStyle = "solarized-dark"
    highlightLanguages = ["go", "haskell", "kotlin", "scala", "swift"]

[Languages]
[Languages.en]
    copyright  = "<a href='https://creativecommons.org/publicdomain/zero/1.0/' style='text-decoration: none; color: #777777'> CC0; no rights reserved </a>"
    description = "Living with self-determination, equality and acceptance"
[[Languages.en.menu.main]]
    url = "/"
    name = "Home"
    weight = 1
[[Languages.en.menu.main]]
    url = "/docs"
    name = "Documents"
    weight = 2
[[Languages.en.menu.main]]
    url = "/contact/"
    name = "Contact"
    weight = 4

[[Languages.en.menu.main]]
    url = "/meetings"
    name = "Meetings"
    weight = 3

[Languages.de]
    copyright  = "<a href='https://creativecommons.org/publicdomain/zero/1.0/' style='text-decoration: none; color: #777777'> CC0; keine Rechte vorbehalten </a>"
    description = "Leben mit Selbstbestimmung, Gleichberechtigung und Akzeptanz"
[[Languages.de.menu.main]]
    url = "/"
    name = "Home"
    weight = 1
[[Languages.de.menu.main]]
    url = "/docs"
    name = "Unterlagen"
    weight = 2
[[Languages.de.menu.main]]
    url = "/contact/"
    name = "Kontakt"
    weight = 4
[[Languages.de.menu.main]]
    url = "/meetings"
    name = "Treffen"
    weight = 3



# Social icons to be shown on the right-hand side of the navigation bar
# The "name" field should match the name of the icon to be used
# The list of available icons can be found at http://fontawesome.io/icons/

[[Languages.en.menu.icon]]
    url = "dmwebb@gmail.com"
    name = "envelope-o"
    weight = 1

[[Languages.en.menu.icon]]
    url = "https://gitlab.com/kanthaus/"
    name = "gitlab"
    weight = 2

[[Languages.en.menu.icon]]
    url = "/index.xml"
    name = "rss"
    weight = 3




[[Languages.de.menu.icon]]
    url = "mailto:dmwebb@gmail.com"
    name = "envelope-o"
    weight = 1

[[Languages.de.menu.icon]]
    url = "https://gitlab.com/kanthaus/"
    name = "gitlab"
    weight = 2

[[Languages.de.menu.icon]]
    url = "/index.xml"
    name = "rss"
    weight = 3
