baseURL = "https://kanthaus.online/"
defaultContentLanguage = "en"
defaultContentLanguageInSubdir = true
title = "Kanthaus"
theme = "minimal"

[params]
    author = "kanthaus"
    accent = "green"
    showBorder = false
    backgroundColor = "white"
    font = "Raleway" # should match the name on Google Fonts!
    highlight = true
    highlightStyle = "solarized-dark"
    highlightLanguages = ["go", "haskell", "kotlin", "scala", "swift"]
    publicGitURL = "https://gitlab.com/kanthaus/kanthaus.gitlab.io"

[Languages]
[Languages.en]
    copyright  = "<a href='https://creativecommons.org/publicdomain/zero/1.0/'> CC0; no rights reserved </a>"

[Languages.de]
    copyright  = "<a href='https://creativecommons.org/publicdomain/zero/1.0/'> CC0; keine Rechte vorbehalten </a>"

# Social icons to be shown on the right-hand side of the navigation bar
# The "name" field should match the name of the icon to be used
# The list of available icons can be found at http://fontawesome.io/icons/

[[Languages.en.menu.icon]]
    url = "mailto:dmwebb@gmail.com"
    name = "envelope-o"
    weight = 1
[[Languages.en.menu.icon]]
    url = "https://gitlab.com/kanthaus/"
    name = "gitlab"
    weight = 2
[[Languages.en.menu.icon]]
    url = "/index.xml"
    name = "rss"
    weight = 3

[[Languages.de.menu.icon]]
    url = "mailto:dmwebb@gmail.com"
    name = "envelope-o"
    weight = 1
[[Languages.de.menu.icon]]
    url = "https://gitlab.com/kanthaus/"
    name = "gitlab"
    weight = 2
[[Languages.de.menu.icon]]
    url = "/index.xml"
    name = "rss"
    weight = 3
